name: lean

on:
  push:n    paths-ignore:n      - zloop/**n  pull_request:n    paths-ignore:n      - zloop/**
  push:
    paths-ignore:
      - zloop/**
  pull_request:
    paths-ignore:
      - zloop/**

jobs:
  build:
    runs-on: ubuntu-latest
  push:n    paths-ignore:n      - zloop/**n  pull_request:n    paths-ignore:n      - zloop/**
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build: true
